openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/profile/:
    get:
      operationId: GetUserProfile
      description: 'Get user profile information'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/profile'
          description: ''
      tags:
      - api
  /api/login/code/:
    post:
      operationId: LoginGetCode
      description: 'First authentication step, send phone number, get a code'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/login-code'
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/code'
          description: ''
      tags:
      - api
  /api/login/:
    post:
      operationId: Login
      description: 'Second authenticatication step, send phone number and code to log in'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/login'
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/profile'
          description: ''
      tags:
      - api
  /api/get-invited/:
    post:
      operationId: GetInvited
      description: 'Send invite code to get invited'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/invite-code'
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/invite-code-accepted'
          description: ''
      tags:
      - api
      
components:
  schemas:
    login-code:
      type: object
      properties:
        phone_number:
          type: string
          pattern: '^7\d{10}$'
    login:
      type: object
      properties:
        phone_number:
          type: string
          pattern: '^7\d{10}$'
        code:
          type: string
          pattern: '^\d{4}$'
    code:
      type: object
      properties:
        status:
          type: string
          enum: ["success"]
        detail:
          type: string
          enum: ["code sent"]
        phone_number:
          type: string
          pattern: '^7\d{10}$'
        code:
          type: string
          pattern: '^\d{4}$'
    profile:
      type: object
      properties:
        user:
          type: string
          pattern: '^7\d{10}$'
        invite_code:
          type: string
          pattern: '[a-z0-9]{6}'
        invited_users:
          type: array
          items:
            type: string
            pattern: '^7\d{10}$'
        code_invited:
          type: string
          pattern: '[a-z0-9]{6}'
    invite-code:
      type: object
      properties:
        invite_code:
          type: string
          pattern: '[a-z0-9]{6}'
    invite-code-accepted:
      type: object
      properties:
        status:
          type: string
          enum: ["success"]
        detail:
          type: string
          enum: ["invite code accepted"]
