# Generated by Django 4.2.4 on 2023-08-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_logincode_phone_number_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="invited",
            new_name="invited_users",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_invited",
            field=models.BooleanField(default=False),
        ),
    ]
