# Generated by Django 4.2.4 on 2023-08-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_invited_profile_invited_users_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_invited",
        ),
        migrations.AddField(
            model_name="profile",
            name="code_invited",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
